import{useMemo,useState}from'react'
import{useAnalyticsQuery,useRespondentAnswersQuery}from'./store'
import'./analytics.css'

const clean=(text='')=>text.replace(/^\[[^\]]+\]\s*/,'')
const duration=(seconds:number|null)=>seconds==null?'—':seconds<60?`${seconds} giây`:`${Math.floor(seconds/60)}p ${seconds%60}s`
const participant=(person:any)=>!person?.name||['bạn','ẩn danh'].includes(String(person.name).toLowerCase())?`Người tham gia #${String(person?.id||'').slice(0,6).toUpperCase()}`:person.name

export default function AnalyticsDashboard(){
 const{data,isLoading,isFetching,refetch}=useAnalyticsQuery();const[view,setView]=useState<'overview'|'questions'|'responses'>('overview');const[query,setQuery]=useState('');const[status,setStatus]=useState('all');const[platform,setPlatform]=useState('all');const[selected,setSelected]=useState<string|null>(null)
 const people=useMemo(()=>data?.respondents?.filter((person:any)=>(status==='all'||person.status===status)&&(platform==='all'||(person.platform||'Chưa xác định')===platform)&&`${person.name} ${person.email} ${person.id}`.toLowerCase().includes(query.toLowerCase()))||[],[data,query,status,platform])
 if(isLoading)return <div className="analytics-loading"><div className="loader"/><p>Đang tổng hợp dữ liệu khảo sát…</p></div>
 if(!data)return <section className="panel empty">Chưa thể tải dữ liệu thống kê.</section>
 return <div className="analytics">
  <div className="analytics-toolbar"><nav><button className={view==='overview'?'active':''} onClick={()=>setView('overview')}>Tổng quan</button><button className={view==='questions'?'active':''} onClick={()=>setView('questions')}>Phân tích câu hỏi</button><button className={view==='responses'?'active':''} onClick={()=>setView('responses')}>Dữ liệu người trả lời</button></nav><button className="analytics-refresh" onClick={()=>refetch()}>↻ {isFetching?'Đang cập nhật':'Làm mới'}</button></div>
  {view==='overview'&&<Overview data={data}/>} {view==='questions'&&<Questions questions={data.questions}/>} {view==='responses'&&<Responses data={data} people={people} query={query} setQuery={setQuery} status={status} setStatus={setStatus} platform={platform} setPlatform={setPlatform} select={setSelected}/>} {selected&&<ResponseDrawer id={selected} close={()=>setSelected(null)}/>} 
 </div>
}

function Overview({data}:{data:any}){const k=data.kpis;return <>
 <div className="bi-kpis"><Kpi label="Tổng lượt tham gia" value={k.total} note={`${k.active} phiếu đang thực hiện`} icon="◎"/><Kpi label="Tỉ lệ hoàn thành" value={`${k.completion_rate}%`} note={`${k.completed} phiếu hoàn tất`} icon="↗"/><Kpi label="Câu trả lời đã ghi" value={k.answers} note="Tổng trên mọi câu hỏi" icon="✓"/><Kpi label="Thời gian trung bình" value={duration(k.average_duration_seconds)} note="Tính trên phiếu hoàn thành" icon="◷"/></div>
 <div className="bi-grid wide"><section className="bi-card"><CardTitle eyebrow="XU HƯỚNG" title="Lượt tham gia 30 ngày gần nhất"/><TrendChart rows={data.daily}/></section><section className="bi-card"><CardTitle eyebrow="FUNNEL" title="Tiến độ hoàn thành"/><div className="funnel"><div style={{'--w':'100%'}as any}><span>Bắt đầu</span><b>{k.total}</b></div><div style={{'--w':`${Math.max(k.completion_rate,8)}%`}as any}><span>Hoàn thành</span><b>{k.completed}</b></div></div><small className="bi-note">Tỉ lệ rời khảo sát: <b>{Math.round((100-k.completion_rate)*10)/10}%</b></small></section></div>
 <div className="bi-grid"><section className="bi-card"><CardTitle eyebrow="PHÂN KHÚC" title="Nền tảng mua sắm"/><Bars rows={data.platforms}/></section><section className="bi-card"><CardTitle eyebrow="PHÂN KHÚC" title="Nhóm sản phẩm quan tâm"/><Bars rows={data.products}/></section><section className="bi-card"><CardTitle eyebrow="HEURISTIC" title="Điểm biến trung bình"/><VariableBars rows={data.variables}/></section></div>
 </>}
function Kpi({label,value,note,icon}:{label:string;value:any;note:string;icon:string}){return <section><header><span>{label}</span><i>{icon}</i></header><strong>{value}</strong><small>{note}</small></section>}
function CardTitle({eyebrow,title}:{eyebrow:string;title:string}){return <header className="bi-title"><span>{eyebrow}</span><h3>{title}</h3></header>}
function TrendChart({rows}:{rows:any[]}){const max=Math.max(1,...rows.map(r=>r.started));if(!rows.length)return <div className="chart-empty">Chưa có dữ liệu theo ngày</div>;const points=rows.map((r,i)=>`${rows.length===1?50:i/(rows.length-1)*100},${92-r.started/max*76}`).join(' ');return <div className="trend"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#e85e8d" stopOpacity=".3"/><stop offset="1" stopColor="#e85e8d" stopOpacity="0"/></linearGradient></defs><polygon points={`0,100 ${points} 100,100`} fill="url(#area)"/><polyline points={points} fill="none" stroke="#d94d7c" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg><div>{rows.map((r,i)=><span key={r.date} style={{left:`${rows.length===1?50:i/(rows.length-1)*100}%`,bottom:`${r.started/max*76}%`}} title={`${r.date}: ${r.started} lượt`}/>)}</div><footer><small>{new Date(rows[0].date).toLocaleDateString('vi')}</small><b>{rows.reduce((sum,r)=>sum+r.started,0)} lượt</b><small>{new Date(rows[rows.length-1].date).toLocaleDateString('vi')}</small></footer></div>}
function Bars({rows}:{rows:any[]}){const max=Math.max(1,...rows.map(r=>r.value));return <div className="bi-bars">{rows.slice(0,7).map(r=><div key={r.label}><header><span>{r.label}</span><b>{r.value}</b></header><i><em style={{width:`${r.value/max*100}%`}}/></i></div>)}</div>}
function VariableBars({rows}:{rows:any[]}){return <div className="variable-bars">{rows.slice(0,8).map(r=><div key={r.code}><b>{r.code}</b><i><em style={{width:`${r.average/5*100}%`}}/></i><span>{r.average}</span></div>)}</div>}

function Questions({questions}:{questions:any[]}){const[search,setSearch]=useState('');const[phase,setPhase]=useState('all');const phases=Array.from(new Set(questions.map(q=>q.phase))) as string[];const shown=questions.filter(q=>(phase==='all'||q.phase===phase)&&`${q.id} ${q.text}`.toLowerCase().includes(search.toLowerCase()));return <><div className="question-filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm mã hoặc nội dung câu hỏi…"/><select value={phase} onChange={e=>setPhase(e.target.value)}><option value="all">Tất cả chặng</option>{phases.map(p=><option key={p}>{p}</option>)}</select><b>{shown.length} câu hỏi</b></div><div className="question-analysis">{shown.map(q=><section key={q.id}><header><div><b>{q.id}</b><span>{q.phase}</span></div><strong>{q.total} lượt trả lời</strong></header><h3>{clean(q.text)}</h3>{q.options.length?<div className="answer-distribution">{q.options.map((o:any,index:number)=><div key={o.id}><header><i>{o.id||'•'}</i><span>{o.label}</span><b>{o.percent}%</b></header><div><em className={`c${index%5}`} style={{width:`${o.percent}%`}}/></div><small>{o.count} lượt chọn</small></div>)}</div>:<p className="no-answer">Chưa có câu trả lời cho câu này.</p>}</section>)}</div></>}

function Responses({data,people,query,setQuery,status,setStatus,platform,setPlatform,select}:{data:any;people:any[];query:string;setQuery:any;status:string;setStatus:any;platform:string;setPlatform:any;select:any}){return <><div className="response-filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm tên, email hoặc mã phiếu…"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Mọi trạng thái</option><option value="completed">Đã hoàn thành</option><option value="active">Đang thực hiện</option></select><select value={platform} onChange={e=>setPlatform(e.target.value)}><option value="all">Mọi nền tảng</option>{data.platforms.map((p:any)=><option key={p.label}>{p.label}</option>)}</select><b>{people.length} phiếu</b></div><section className="response-table"><table><thead><tr><th>Người tham gia</th><th>Phân khúc</th><th>Tiến độ</th><th>Hoàn thành lúc</th><th>Thời lượng</th><th>Điểm H</th><th/></tr></thead><tbody>{people.map(person=><tr key={person.id} onClick={()=>select(person.id)}><td><b>{participant(person)}</b><small>{person.email||person.id.slice(0,12)}</small></td><td>{person.platform||'—'}<small>{person.product||'Chưa chọn sản phẩm'}</small></td><td><span className={`bi-status ${person.status}`}>{person.status==='completed'?'Hoàn thành':'Đang làm'}</span><small>{person.answer_count} câu trả lời</small></td><td>{person.completed_at?new Date(person.completed_at).toLocaleString('vi'):'Chưa xong'}</td><td>{duration(person.duration_seconds)}</td><td><strong>{person.score??'—'}</strong></td><td><button>Xem form →</button></td></tr>)}</tbody></table>{!people.length&&<div className="chart-empty">Không tìm thấy phiếu phù hợp.</div>}</section></>}

function ResponseDrawer({id,close}:{id:string;close:()=>void}){const{data,isLoading}=useRespondentAnswersQuery(id);const person=data?.respondent;return <div className="drawer-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="response-drawer"><header className="drawer-hero"><div className="drawer-avatar">{participant(person).replace('Người tham gia #','').slice(0,2).toUpperCase()}</div><div><span>HỒ SƠ PHẢN HỒI</span><h2>{participant(person)}</h2><small>{person?.email||`Mã phiếu · ${id.slice(0,12)}`}</small></div><button onClick={close}>×</button></header>{isLoading?<div className="analytics-loading"><div className="loader"/></div>:<><div className="drawer-summary"><div><span>TIẾN ĐỘ</span><b>{data?.answers?.length||0} câu</b><em className={person?.status}>{person?.status==='completed'?'Đã hoàn thành':'Đang thực hiện'}</em></div><div><span>BẮT ĐẦU</span><b>{person?.started_at?new Date(person.started_at).toLocaleDateString('vi'):'—'}</b><small>{person?.started_at?new Date(person.started_at).toLocaleTimeString('vi',{hour:'2-digit',minute:'2-digit'}):''}</small></div><div><span>HOÀN THÀNH</span><b>{person?.completed_at?new Date(person.completed_at).toLocaleDateString('vi'):'Chưa xong'}</b><small>{person?.completed_at?new Date(person.completed_at).toLocaleTimeString('vi',{hour:'2-digit',minute:'2-digit'}):''}</small></div></div><div className="drawer-context"><span>🛍 {person?.product||'Chưa chọn sản phẩm'}</span><span>♡ {person?.platform||'Chưa chọn nền tảng'}</span></div><div className="answers-heading"><div><span>HÀNH TRÌNH TRẢ LỜI</span><h3>Từng lựa chọn trong form</h3></div><b>{data?.answers?.length||0} mục</b></div><div className="form-answers timeline">{data?.answers?.map((answer:any,index:number)=><article key={answer.question_id}><div className="timeline-index"><i>{String(index+1).padStart(2,'0')}</i><span/></div><div className="answer-body"><header><span>{answer.phase}</span><b>{answer.question_id}</b><time>{answer.answered_at?new Date(answer.answered_at).toLocaleTimeString('vi',{hour:'2-digit',minute:'2-digit',second:'2-digit'}):''}</time></header><h3>{clean(answer.question)}</h3><p><b>{answer.option_id}</b><span>{String(answer.answer??'—')}</span></p>{Object.keys(answer.scores||{}).length>0&&<footer>{Object.entries(answer.scores).map(([key,value])=><span key={key}>{key}<b>{String(value)}</b></span>)}</footer>}</div></article>)}</div></>}</aside></div>}
