import{useEffect,useState}from'react';import{useDispatch,useSelector}from'react-redux';import type{RootState}from'./store';import{setSession,useAnswerMutation,useNextQuery,useStartMutation}from'./store';
import{Link}from'react-router-dom';
import{mediaUrl}from'./config';
import'./text-answer.css';
import'./survey-experience.css';
import'./media-options.css';
import'./likert-icons.css';
import'./theme-pink.css';
import'./context-memory.css';
import'./adaptive-themes.css';

const phaseIcon:Record<string,string>={'Trước mua':'✦','Đang mua':'◉','Cá nhân hoá':'♡','Mua lặp lại':'↻','Kết phiên':'✓'}
document.documentElement.dataset.surveyTheme=localStorage.getItem('survey_session')?(localStorage.getItem('survey_theme')||'rose'):'rose';
function RichQuestion({text}:{text:string}){const clean=text.replace(/^\[[^\]]+\]\s*/,'');const parts=clean.split(/(“[^”]+”|"[^"]+"|\b\d+[\w.%–-]*|flash sale|voucher|Shopee|TikTok Shop|SPayLater)/gi);return <>{parts.map((part,i)=>/^(“|"|\d|flash sale|voucher|Shopee|TikTok Shop|SPayLater)/i.test(part)?<mark key={i}>{part}</mark>:<span key={i}>{part}</span>)}</>}
export default function Survey(){const id=useSelector((s:RootState)=>s.session.id);const dispatch=useDispatch();const[start,{isLoading}]=useStartMutation();const[email,setEmail]=useState('');const[textAnswer,setTextAnswer]=useState('');const[reaction,setReaction]=useState('');const[consent,setConsent]=useState(true);const{data,isFetching,error}=useNextQuery(id!,{skip:!id});const[answer,{isLoading:saving}]=useAnswerMutation();
 useEffect(()=>{if(!id||data?.question?.id==='P00'||data?.question?.id==='P01c'){localStorage.setItem('survey_theme','rose');document.documentElement.dataset.surveyTheme='rose'}},[id,data?.question?.id]);
 useEffect(()=>{const src=mediaUrl(data?.question?.image_url);document.documentElement.dataset.hasQuestionImage=src?'true':'false';if(src)document.documentElement.style.setProperty('--question-image',`url("${src}")`);else document.documentElement.style.removeProperty('--question-image')},[data?.question?.image_url]);
 async function begin(){if(!consent)return;localStorage.setItem('survey_theme','rose');document.documentElement.dataset.surveyTheme='rose';const x=await start({name:'bạn',email:email||undefined,consent}).unwrap();dispatch(setSession(x.id))}
 async function choose(option:string,value?:string){if(id&&data?.question){if(data.question.id==='P01c'){const theme:{[key:string]:string}={A:'rose',B:'mint',C:'sunset',D:'lavender'};localStorage.setItem('survey_theme',theme[option]||'rose');document.documentElement.dataset.surveyTheme=theme[option]||'rose'}setReaction(['Đã ghi nhận — rất bạn ✦','Nice choice! Tiếp tục nha →','Một mảnh ghép nữa đã mở ✨'][Math.floor(Math.random()*3)]);await answer({id,question_id:data.question.id,option_id:option,value}).unwrap();setTextAnswer('');window.setTimeout(()=>setReaction(''),1200)}}
 if(!id)return <div className="survey-shell"><header className="brand"><span className="logo">G</span><span>GROUP2</span><small>GEN Z INSIGHT</small></header><main className="welcome"><span className="eyebrow">KHẢO SÁT HÀNH VI MUA SẮM · 2026</span><h1>Mua sắm online<br/><em>nói gì về bạn?</em></h1><p>Không có đúng hay sai. Chỉ có những lựa chọn rất “bạn” — và tụi mình muốn lắng nghe.</p><div className="facts"><span>⏱ 8–10 phút</span><span>◌ Ẩn danh</span><span>✦ Cá nhân hoá</span></div><section className="start-card"><input placeholder="Email (không bắt buộc)" value={email} onChange={e=>setEmail(e.target.value)}/><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Tôi đồng ý tham gia và cho phép dùng câu trả lời cho mục đích nghiên cứu.</label><button className="primary" disabled={!consent||isLoading} onClick={begin}>Bắt đầu khám phá <b>→</b></button></section></main><footer><Link to="/admin">Dành cho quản trị viên</Link></footer></div>
 if(error)return <main className="center"><h2>Không kết nối được máy chủ</h2><p>Hãy kiểm tra backend đang chạy ở cổng 8000.</p></main>
 if(isFetching&&!data)return <main className="center"><div className="loader"/></main>
 if(data?.done){const r=data.result||{};return <div className="finish persona-page"><div className="persona-orbit"><i>✦</i><i>♡</i><i>⚡</i></div><span className="eyebrow">SHOPPING DNA · ĐÃ GIẢI MÃ</span><h1>Dấu ấn mua sắm<br/><em>của riêng bạn</em></h1><section className="persona-card"><span className="persona-kicker">CHÂN DUNG NỔI BẬT</span><h2>{r.profile?.title}</h2><p>{r.profile?.description}</p><div className="trait-list">{r.traits?.map((t:any)=><div key={t.label}><header><b>{t.label}</b><strong>{t.value}%</strong></header><span><i style={{width:`${t.value}%`}}/></span></div>)}</div></section><section className="advice-card"><span>💌</span><div><h3>Một chút nhắn gửi cho chiếc ví</h3>{r.advice?.map((a:string,i:number)=><p key={i}><b>{String(i+1).padStart(2,'0')}</b>{a}</p>)}</div></section><p className="result-note">{r.note}</p><button className="restart" onClick={()=>dispatch(setSession(null))}>Khám phá lại một phiên bản khác ↻</button></div>}
 const q=data?.question;if(!q)return null;const phaseCopy:Record<string,string>={'Mở đầu':'Bắt sóng với bạn trước nha','Trước mua':'Nếu deal xuất hiện ngay lúc này...','Kiểm tra tập trung':'Một checkpoint siêu nhanh','Đang mua':'Giỏ hàng đang chờ quyết định','Cá nhân hoá':'Từ đây câu chuyện là của riêng bạn','Mua lặp lại':'Khi app đã bắt đầu hiểu gu bạn','Kết phiên':'Chạm cuối để giải mã shopping DNA','Nhân khẩu học':'Vài nét cuối cho bức chân dung'};return <div className={'question-page kind-'+q.kind}>{reaction&&<div className="reaction-pop">{reaction}</div>}<header className="q-head"><div className="brand"><span className="logo">G</span><span>GROUP2</span></div><div className="step-count"><b>{data.answered||0}</b><span>/ {data.total}</span></div></header><div className="progress"><i style={{width:`${data.progress}%`}}/></div><main className="question-wrap"><div className="chapter-copy">{phaseCopy[q.phase]||'Chọn điều giống bạn nhất'}</div><div className="question-meta"><span>{phaseIcon[q.phase]||'✦'} {q.phase}</span><b>{q.id}</b></div>{data.context&&(data.context.product||data.context.platform)&&<div className="context-memory"><small>BỐI CẢNH CỦA RIÊNG BẠN</small>{data.context.product&&<span>🛍 {data.context.product}</span>}{data.context.platform&&<span>♡ {data.context.platform}</span>}</div>}<section className="scenario-card"><span className="quote-mark">“</span><h2><RichQuestion text={q.text}/></h2></section>{q.kind==='text'?<div className="text-answer"><input autoFocus placeholder="Nickname của bạn (có thể bỏ trống)" value={textAnswer} onChange={e=>setTextAnswer(e.target.value)} onKeyDown={e=>e.key==='Enter'&&choose('A',textAnswer)}/><button className="primary" onClick={()=>choose('A',textAnswer)}>Tiếp tục →</button></div>:<div className={q.kind==='likert'?'options likert':'options'}>{q.kind==='likert'&&<div className="likert-guide">Mức độ câu này giống bạn đến đâu?</div>}{q.options.map((o,i)=><button aria-label={o.label} title={q.kind==='likert'?o.label:undefined} className={(o.image_url?'has-image ':'')+(q.kind==='likert'?'emoji-choice':'')} key={o.id} disabled={saving||Boolean(reaction)} onClick={()=>choose(o.id)}>{q.kind==='likert'?<span className="emoji-only">{o.label.trim().split(/\s+/)[0]}</span>:<><b>{String.fromCharCode(65+i)}</b><span>{o.image_url&&<img src={o.image_url} alt=""/>}{o.label}</span><i>→</i></>}</button>)}</div>}<p className="hint"><span>🔒 Điểm được bảo vệ</span><span>⚡ Tự lưu sau mỗi chọn</span></p></main></div>}
