import{useEffect,useRef,useState}from'react';import{useDispatch,useSelector}from'react-redux';import type{RootState}from'./store';import{api,setSession,useAnswerBatchMutation,useBackMutation,useStartMutation}from'./store';
import type{Manifest,Next}from'./types';
import{Link}from'react-router-dom';
import{apiUrl,mediaUrl}from'./config';
import'./text-answer.css';
import'./survey-experience.css';
import'./media-options.css';
import'./likert-icons.css';
import'./theme-pink.css';
import'./context-memory.css';
import'./adaptive-themes.css';
import'./back-navigation.css';
import{cachedManifest,cacheManifest,checkpointCommitted,checkpointFailed,drafts,latestDraft,localSession,markSynced,patchLocalSession,pendingDrafts,prepareCheckpoint,removeDraft,removeDrafts,saveDraft,saveLocalSession,syncState}from'./survey-draft';

const phaseIcon:Record<string,string>={'Trước mua':'✦','Đang mua':'◉','Cá nhân hoá':'♡','Mua lặp lại':'↻','Kết phiên':'✓'}
function pipeText(text:string,context:Next['context'],nickname=''){return text.replaceAll('{PLATFORM}',context?.platform||'nền tảng bạn thường dùng').replaceAll('{PRODUCT}',context?.product||'sản phẩm bạn quan tâm').replaceAll('{NAME}',nickname.trim()||'bạn')}
function personalizeQuestion(question:Manifest['questions'][number],context:Next['context'],nickname:string){let options=question.options;if(question.id==='P01b'&&context?.product){const groups=['Thời trang','Mỹ phẩm','Công nghệ','Gia dụng'];const index=Math.max(0,groups.findIndex(name=>context.product?.toLowerCase().includes(name.toLowerCase())));const source=options[Math.min(index,options.length-1)]?.label||'';options=source.split(':',2).at(-1)!.split('·').map((label,i)=>({id:String.fromCharCode(65+i),label:label.trim()}));options.push({id:'F',label:'Món khác trong nhóm này'})}return{...question,text:pipeText(question.text,context,nickname),options:options.map(option=>({...option,label:pipeText(option.label,context,nickname)}))}}
function optimisticNext(manifest:Manifest,currentId:string,answered:{question_id:string;option_id:string;value?:string}[],context:Next['context']):Next|null{const answerMap=Object.fromEntries(answered.map(a=>[a.question_id,a.option_id]));const answeredIds=new Set(answered.map(a=>a.question_id));const nickname=answered.find(a=>a.question_id==='P00')?.value||'';const start=currentId?manifest.questions.findIndex(q=>q.id===currentId):-1;for(const question of manifest.questions.slice(start+1)){if(answeredIds.has(question.id))continue;const blocked=manifest.branches.filter(rule=>rule.target_question===question.id).some(rule=>{const actual=answerMap[rule.source_question];const match=String(actual)===rule.expected_value;return(rule.action==='skip'&&(rule.operator==='not_equals'?!match:match))||(rule.action==='show_if'&&!(rule.operator==='not_equals'?!match:match))});if(!blocked)return{done:false,question:personalizeQuestion(question,context,nickname),answered:answered.length,total:manifest.questions.length,progress:Math.round(answered.length/manifest.questions.length*100),context}}if(answered.length)return{done:false,question:{id:'__SYNC__',position:manifest.questions.length+1,phase:'Kết phiên',kind:'status',text:'Câu trả lời đã nằm an toàn trên thiết bị. Tụi mình đang đồng bộ để mở dấu ấn mua sắm của riêng bạn.',variables:[],options:[],active:true},answered:answered.length,total:manifest.questions.length,progress:100,context};return null}
function RichQuestion({text}:{text:string}){const piped=pipeText(text,{platform:localStorage.getItem('survey_platform')||undefined,product:localStorage.getItem('survey_product')||undefined},localStorage.getItem('survey_nickname')||'');const clean=piped.replace(/^\[[^\]]+\]\s*/,'');const parts=clean.split(/(“[^”]+”|"[^"]+"|\b\d+[\w.%–-]*|flash sale|voucher|Shopee|TikTok Shop|SPayLater)/gi);return <>{parts.map((part,i)=>/^(“|"|\d|flash sale|voucher|Shopee|TikTok Shop|SPayLater)/i.test(part)?<mark key={i}>{part}</mark>:<span key={i}>{part}</span>)}</>}
export default function Survey(){const id=useSelector((s:RootState)=>s.session.id);const dispatch=useDispatch<any>();const[start,{isLoading}]=useStartMutation();const[email,setEmail]=useState('');const[textAnswer,setTextAnswer]=useState('');const[nickname,setNickname]=useState(localStorage.getItem('survey_nickname')||'');const[reaction,setReaction]=useState('');const[syncLabel,setSyncLabel]=useState('Đã lưu trên thiết bị');const[consent,setConsent]=useState(true);const[theme,setTheme]=useState(localStorage.getItem('survey_theme')||'rose');const[manifest,setManifest]=useState<Manifest|null>(null);const[data,setLocalData]=useState<Next|null>(null);const[manifestLoading,setManifestLoading]=useState(true);const[sendBatch,{isLoading:saving}]=useAnswerBatchMutation();const[back,{isLoading:goingBack}]=useBackMutation();const syncing=useRef(false);const syncTimer=useRef<number|undefined>(undefined);const questionStarted=useRef(Date.now());
 const[,setContextVersion]=useState(0);
 useEffect(()=>{if(!id||data?.question?.id==='P00'||data?.question?.id==='P01c'){localStorage.setItem('survey_theme','rose');setTheme('rose')}},[id,data?.question?.id]);
 async function getPublicManifest(){const stored=await cachedManifest<Manifest>();try{const response=await fetch('/survey-manifest.json',{cache:'no-cache'});if(!response.ok)throw new Error('Manifest unavailable');const bundled=await response.json() as Manifest;if(!bundled.questions?.length)throw new Error('Manifest empty');const value=stored?.value&&stored.value.version>bundled.version?stored.value:bundled;await cacheManifest(value,value.version);setManifest(value);return value}catch{if(stored?.value?.questions?.length){setManifest(stored.value);return stored.value}throw new Error('Không tải được bộ khảo sát')}}
 useEffect(()=>{let active=true;void getPublicManifest().catch(()=>active&&setManifest(null)).finally(()=>active&&setManifestLoading(false));void fetch(apiUrl('manifest')).then(response=>response.ok?response.json():null).then(async(value:Manifest|null)=>{if(!active||!value?.questions?.length)return;await cacheManifest(value,value.version);if(!localStorage.getItem('survey_session'))setManifest(value)}).catch(()=>{});return()=>{active=false}},[]);
 useEffect(()=>{const root=document.getElementById('root');if(!root)return;root.dataset.surveyTheme=theme;root.classList.add('survey-theme-scope');return()=>{delete root.dataset.surveyTheme;root.classList.remove('survey-theme-scope')}},[theme]);
 useEffect(()=>{const root=document.getElementById('root');if(!root)return;const src=mediaUrl(data?.question?.image_url);root.dataset.hasQuestionImage=src?'true':'false';if(src)root.style.setProperty('--question-image',`url("${src}")`);else root.style.removeProperty('--question-image');return()=>{delete root.dataset.hasQuestionImage;root.style.removeProperty('--question-image')}},[data?.question?.image_url]);
 useEffect(()=>{questionStarted.current=Date.now()},[data?.question?.id]);
 useEffect(()=>{const label=document.querySelector('.hint span:last-child');if(label)label.textContent=`⚡ ${syncLabel}`},[syncLabel,data?.question?.id]);
 useEffect(()=>{if(data?.context?.platform)localStorage.setItem('survey_platform',data.context.platform);if(data?.context?.product)localStorage.setItem('survey_product',data.context.product);if(data?.context?.platform||data?.context?.product)setContextVersion(value=>value+1)},[data?.context?.platform,data?.context?.product]);
 useEffect(()=>{if(!id||!manifest)return;void(async()=>{let session=await localSession(id);if(!session){session={session_id:id,consent:true,started_at:new Date().toISOString(),manifest_version:manifest.version,remote_created:true,context:{theme:localStorage.getItem('survey_theme')||'rose'}};await saveLocalSession(session)}const all=await drafts(id);const context={product:session.context.product,platform:session.context.platform,theme:session.context.theme};setTheme(session.context.theme||'rose');setNickname(session.context.nickname||'');const current=optimisticNext(manifest,all.at(-1)?.question_id||'',all,context);if(current)setLocalData(current)})()},[id,manifest?.version]);
 async function begin(){if(!consent)return;const activeManifest=manifest||await getPublicManifest();const sid=crypto.randomUUID(),started_at=new Date().toISOString();localStorage.setItem('survey_theme','rose');localStorage.removeItem('survey_nickname');localStorage.removeItem('survey_platform');localStorage.removeItem('survey_product');setNickname('');setTheme('rose');await saveLocalSession({session_id:sid,email:email||undefined,consent,started_at,manifest_version:activeManifest.version,remote_created:false,context:{theme:'rose'}});setLocalData(optimisticNext(activeManifest,'',[],{theme:'rose'}));dispatch(setSession(sid))}
 async function ensureRemoteSession(){if(!id)return;const session=await localSession(id);if(!session||session.remote_created)return;await start({id,name:'Ẩn danh',email:session.email,consent:session.consent,started_at:session.started_at,manifest_version:session.manifest_version}).unwrap();await patchLocalSession(id,{remote_created:true})}
 async function flushQueue(force=false){if(!id||syncing.current)return;if(!navigator.onLine){setSyncLabel('Đã lưu trên thiết bị · chờ mạng');return}try{await ensureRemoteSession()}catch{setSyncLabel('Đã lưu trên thiết bị · máy chủ đang khởi động');window.clearTimeout(syncTimer.current);syncTimer.current=window.setTimeout(()=>flushQueue(true),2500);return}const pending=await pendingDrafts(id);if(!pending.length){setSyncLabel('Đã lưu an toàn');return}if(!force&&pending.length<10){window.clearTimeout(syncTimer.current);syncTimer.current=window.setTimeout(()=>flushQueue(true),30000);return}const existing=await syncState(id);if(existing?.next_retry_at&&existing.next_retry_at>Date.now()){window.clearTimeout(syncTimer.current);syncTimer.current=window.setTimeout(()=>flushQueue(true),existing.next_retry_at-Date.now());return}syncing.current=true;setSyncLabel('Đang đồng bộ…');const prepared=await prepareCheckpoint(id,pending.slice(0,10).map(a=>a.question_id));const batch=pending.filter(a=>prepared.question_ids?.includes(a.question_id));try{const result=await sendBatch({id,revision:prepared.revision,idempotency_key:prepared.idempotency_key!,answers:batch.map(({question_id,option_id,value,duration_ms})=>({question_id,option_id,value,duration_ms}))}).unwrap();if(!result.committed)throw new Error('Checkpoint chưa được xác nhận');const ids=await checkpointCommitted(id,result.revision);await markSynced(id,ids);if(result.rejected)await removeDrafts(id,batch.slice(result.accepted).map(a=>a.question_id));setSyncLabel(result.next.done?'Hoàn thành · dữ liệu đã lưu':'Đã lưu an toàn');setLocalData(result.next);dispatch(api.util.updateQueryData('next',id,draft=>Object.assign(draft,result.next)))}catch(error:any){const delay=await checkpointFailed(id,error?.data?.detail||error?.message||'Mất kết nối');setSyncLabel('Đã lưu trên thiết bị · sẽ thử lại');window.clearTimeout(syncTimer.current);syncTimer.current=window.setTimeout(()=>flushQueue(true),delay||2000)}finally{syncing.current=false;const remaining=await pendingDrafts(id);if(remaining.length>=10)void flushQueue(true)}}
 async function goBack(){if(!id||goingBack||saving||!manifest)return;setReaction('');setTextAnswer('');const latest=await latestDraft(id);if(latest&&!latest.synced){await removeDraft(id,latest.question_id);const session=await localSession(id);const all=await drafts(id);const context=session?{product:session.context.product,platform:session.context.platform,theme:session.context.theme}:data?.context;const question=personalizeQuestion(manifest.questions.find(q=>q.id===latest.question_id)!,context,session?.context.nickname||'');setLocalData({done:false,question,answered:all.length,total:manifest.questions.length,progress:Math.round(all.length/manifest.questions.length*100),context});return}const result=await back(id).unwrap();if(latest)await removeDraft(id,latest.question_id);setLocalData(result.next);if(result.next.question?.id==='P01c'){localStorage.setItem('survey_theme','rose');setTheme('rose')}}
 async function choose(option:string,value?:string){if(id&&data?.question&&manifest){const question=data.question,selected=question.options.find(item=>item.id===option);const session=await localSession(id);const context={...(session?.context||{theme}),theme:session?.context.theme||theme};if(question.id==='P00'){const entered=(value||'').trim();context.nickname=entered;if(entered)localStorage.setItem('survey_nickname',entered);else localStorage.removeItem('survey_nickname');setNickname(entered)}if(question.id==='P01a'&&selected)context.product=selected.label;if(question.id==='P01b'&&selected)context.product=selected.label;if(question.id==='P02'&&selected)context.platform=selected.label;if(question.id==='P01c'){const themes:{[key:string]:string}={A:'rose',B:'mint',C:'sunset',D:'lavender'};context.theme=themes[option]||'rose';localStorage.setItem('survey_theme',context.theme);setTheme(context.theme)}if(context.product)localStorage.setItem('survey_product',context.product);if(context.platform)localStorage.setItem('survey_platform',context.platform);await patchLocalSession(id,{context});setReaction(['Đã ghi nhận — rất bạn ✦','Nice choice! Tiếp tục nha →','Một mảnh ghép nữa đã mở ✨'][Math.floor(Math.random()*3)]);await saveDraft({session_id:id,question_id:question.id,option_id:option,value,answered_at:new Date().toISOString(),duration_ms:Date.now()-questionStarted.current,synced:false});const all=await drafts(id);const next=optimisticNext(manifest,question.id,all,{product:context.product,platform:context.platform,theme:context.theme});setLocalData(next);await patchLocalSession(id,{current_question_id:next?.question?.id,context});setTextAnswer('');window.setTimeout(()=>setReaction(''),1200);void flushQueue(next?.question?.id==='__SYNC__')}}
 useEffect(()=>{if(!id||!manifest)return;void flushQueue(true);const resume=()=>void flushQueue(true);window.addEventListener('online',resume);return()=>window.removeEventListener('online',resume)},[id,manifest?.version]);
 if(!id)return <div className="survey-shell"><header className="brand"><span className="logo">G</span><span>GROUP2</span><small>GEN Z INSIGHT</small></header><main className="welcome"><span className="eyebrow">KHẢO SÁT HÀNH VI MUA SẮM · 2026</span><h1>Mua sắm online<br/><em>nói gì về bạn?</em></h1><p>Không có đúng hay sai. Chỉ có những lựa chọn rất “bạn” — và tụi mình muốn lắng nghe.</p><div className="facts"><span>⏱ 8–10 phút</span><span>◌ Ẩn danh</span><span>✦ Cá nhân hoá</span></div><section className="start-card"><input placeholder="Email (không bắt buộc)" value={email} onChange={e=>setEmail(e.target.value)}/><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Tôi đồng ý tham gia và cho phép dùng câu trả lời cho mục đích nghiên cứu.</label><button className="primary" disabled={!consent||manifestLoading||!manifest||isLoading} onClick={begin}>{manifestLoading?'Đang chuẩn bị…':'Bắt đầu khám phá'} <b>→</b></button></section></main><footer><Link to="/admin">Dành cho quản trị viên</Link></footer></div>
 if(!data)return <main className="center"><div className="loader"/><p>Đang khôi phục khảo sát trên thiết bị…</p></main>
 if(data?.done){const r=data.result||{};return <div className="finish persona-page"><button className="finish-back" disabled={goingBack} onClick={goBack}>← Đổi câu trả lời cuối</button><div className="persona-orbit"><i>✦</i><i>♡</i><i>⚡</i></div><span className="eyebrow">SHOPPING DNA · ĐÃ GIẢI MÃ</span><h1>Dấu ấn mua sắm<br/><em>của riêng bạn</em></h1><section className="persona-card"><span className="persona-kicker">CHÂN DUNG NỔI BẬT</span><h2>{r.profile?.title}</h2><p>{r.profile?.description}</p><div className="trait-list">{r.traits?.map((t:any)=><div key={t.label}><header><b>{t.label}</b><strong>{t.value}%</strong></header><span><i style={{width:`${t.value}%`}}/></span></div>)}</div></section><section className="advice-card"><span>💌</span><div><h3>Một chút nhắn gửi cho chiếc ví</h3>{r.advice?.map((a:string,i:number)=><p key={i}><b>{String(i+1).padStart(2,'0')}</b>{a}</p>)}</div></section><p className="result-note">{r.note}</p><button className="restart" onClick={()=>dispatch(setSession(null))}>Khám phá lại một phiên bản khác ↻</button></div>}
 const q=data?.question;if(!q)return null;const phaseCopy:Record<string,string>={'Mở đầu':'Bắt sóng với bạn trước nha','Trước mua':'Nếu deal xuất hiện ngay lúc này...','Kiểm tra tập trung':'Một checkpoint siêu nhanh','Đang mua':'Giỏ hàng đang chờ quyết định','Cá nhân hoá':'Từ đây câu chuyện là của riêng bạn','Mua lặp lại':'Khi app đã bắt đầu hiểu gu bạn','Kết phiên':'Chạm cuối để giải mã shopping DNA','Nhân khẩu học':'Vài nét cuối cho bức chân dung'};return <div className={'question-page kind-'+q.kind}>{reaction&&<div className="reaction-pop">{reaction}</div>}<header className="q-head"><div className="brand"><span className="logo">G</span><span>GROUP2</span></div><div className="head-progress">{Boolean(data.answered)&&<button className="survey-back" disabled={goingBack||saving} onClick={goBack}>← <span>Câu trước</span></button>}<div className="step-count"><b>{data.answered||0}</b><span>/ {data.total}</span></div></div></header><div className="progress"><i style={{width:`${data.progress}%`}}/></div><main className="question-wrap"><div className="chapter-copy">{phaseCopy[q.phase]||'Chọn điều giống bạn nhất'}</div><div className="question-meta"><span>{phaseIcon[q.phase]||'✦'} {q.phase}</span><b>{q.id}</b></div>{data.context&&(data.context.product||data.context.platform)&&<div className="context-memory"><small>BỐI CẢNH CỦA RIÊNG BẠN</small>{data.context.product&&<span>🛍 {data.context.product}</span>}{data.context.platform&&<span>♡ {data.context.platform}</span>}</div>}<section className="scenario-card"><span className="quote-mark">“</span><h2><RichQuestion text={q.text}/></h2></section>{q.kind==='text'?<div className="text-answer"><input autoFocus placeholder="Nickname của bạn (có thể bỏ trống)" value={textAnswer} onChange={e=>setTextAnswer(e.target.value)} onKeyDown={e=>e.key==='Enter'&&choose('A',textAnswer)}/><button className="primary" onClick={()=>choose('A',textAnswer)}>Tiếp tục →</button></div>:<div className={q.kind==='likert'?'options likert':'options'}>{q.kind==='likert'&&<div className="likert-guide">Mức độ câu này giống bạn đến đâu?</div>}{q.options.map((o,i)=><button aria-label={o.label} title={q.kind==='likert'?o.label:undefined} className={(o.image_url?'has-image ':'')+(q.kind==='likert'?'emoji-choice':'')} key={o.id} disabled={saving||goingBack||Boolean(reaction)} onClick={()=>choose(o.id)}>{q.kind==='likert'?<span className="emoji-only">{o.label.trim().split(/\s+/)[0]}</span>:<><b>{String.fromCharCode(65+i)}</b><span>{o.image_url&&<img src={o.image_url} alt=""/>}{o.label}</span><i>→</i></>}</button>)}</div>}<p className="hint"><span>🔒 Điểm được bảo vệ</span><span>⚡ Tự lưu sau mỗi chọn</span></p></main></div>}
