export type DraftAnswer={session_id:string;question_id:string;option_id:string;value?:string;answered_at:string;duration_ms?:number;synced:boolean}
export type SyncCheckpoint={session_id:string;revision:number;committed_revision:number;idempotency_key?:string;question_ids?:string[];attempts:number;next_retry_at?:number;last_error?:string;status:'idle'|'syncing'|'retrying'|'committed'}

const DB='group2-survey',ANSWERS='answers',SYNC='sync'
function database(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB,2);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(ANSWERS)){const store=db.createObjectStore(ANSWERS,{keyPath:['session_id','question_id']});store.createIndex('session_id','session_id')}if(!db.objectStoreNames.contains(SYNC))db.createObjectStore(SYNC,{keyPath:'session_id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function transaction<T>(storeName:string,mode:IDBTransactionMode,run:(store:IDBObjectStore,done:(value:T)=>void)=>void){const db=await database();return new Promise<T>((resolve,reject)=>{let result:T;const tx=db.transaction(storeName,mode);run(tx.objectStore(storeName),value=>{result=value});tx.onerror=()=>reject(tx.error);tx.oncomplete=()=>{db.close();resolve(result)}})}
export async function saveDraft(answer:DraftAnswer){return transaction<void>(ANSWERS,'readwrite',(store,done)=>{store.put(answer);done()})}
export async function drafts(session_id:string){return transaction<DraftAnswer[]>(ANSWERS,'readonly',(store,done)=>{const request=store.index('session_id').getAll(session_id);request.onsuccess=()=>done(request.result.sort((a,b)=>a.answered_at.localeCompare(b.answered_at)))})}
export async function pendingDrafts(session_id:string){return(await drafts(session_id)).filter(answer=>!answer.synced)}
export async function markSynced(session_id:string,ids:string[]){const all=await drafts(session_id);return transaction<void>(ANSWERS,'readwrite',(store,done)=>{all.filter(a=>ids.includes(a.question_id)).forEach(a=>store.put({...a,synced:true}));done()})}
export async function removeDraft(session_id:string,question_id:string){return transaction<void>(ANSWERS,'readwrite',(store,done)=>{store.delete([session_id,question_id]);done()})}
export async function removeDrafts(session_id:string,ids:string[]){return transaction<void>(ANSWERS,'readwrite',(store,done)=>{ids.forEach(id=>store.delete([session_id,id]));done()})}
export async function latestDraft(session_id:string){const all=await drafts(session_id);return all.at(-1)}
export async function syncState(session_id:string){return transaction<SyncCheckpoint|undefined>(SYNC,'readonly',(store,done)=>{const request=store.get(session_id);request.onsuccess=()=>done(request.result)})}
export async function prepareCheckpoint(session_id:string,question_ids:string[]){const current=await syncState(session_id);if(current?.idempotency_key&&current.question_ids?.length)return current;const committed=current?.committed_revision||0;const next:SyncCheckpoint={session_id,revision:committed+1,committed_revision:committed,idempotency_key:`${session_id}:${committed+1}:${crypto.randomUUID()}`,question_ids,attempts:0,status:'syncing'};await transaction<void>(SYNC,'readwrite',(store,done)=>{store.put(next);done()});return next}
export async function checkpointFailed(session_id:string,error:string){const current=await syncState(session_id);if(!current)return;const attempts=current.attempts+1;const delay=Math.min(60000,1000*2**Math.min(attempts,6))+Math.floor(Math.random()*500);await transaction<void>(SYNC,'readwrite',(store,done)=>{store.put({...current,attempts,next_retry_at:Date.now()+delay,last_error:error,status:'retrying'});done()});return delay}
export async function checkpointCommitted(session_id:string,revision:number){const current=await syncState(session_id);await transaction<void>(SYNC,'readwrite',(store,done)=>{store.put({session_id,revision,committed_revision:revision,attempts:0,status:'committed'} satisfies SyncCheckpoint);done()});return current?.question_ids||[]}
